config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get 'home/about'=>'homes#about'
  get '/search', to: 'searches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    if @comment.save
    else
      @new_book = Book.new
      @book = book
      @book_comment = @comment
      @book_comments = @book.book_comments
      flash.now[:alert] = "コメントを入力してください。"
      render 'books/show'
    end
  end

  def destroy
    BookComment.find(params[:id]).destroy
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_counter.html.erb
コメント数： <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, rows:'5', placeholder: "コメントをここに", class: "w-100", id: "comment_textarea" %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
    <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book_comment.user) do %>
          <%= image_tag book_comment.user.get_profile_image, size: "50x50" %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-sm btn-danger float-end", remote: true %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$('#comment_counter').html("<%= j(render 'book_comments/counter', book: @comment.book) %>");
$('#comment_index').html("<%= j(render 'book_comments/index', book: @comment.book) %>");
$('#comment_textarea').val("");

app/views/book_comments/destroy.js.erb
$('#comment_counter').html("<%= j(render 'book_comments/counter', book: @comment.book) %>");
$('#comment_index').html("<%= j(render 'book_comments/index', book: @comment.book) %>");