config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get 'home/about'=>'homes#about'
  get '/search', to: 'searches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
  end
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end
  
  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to  request.referer
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% options ||= {} %>

<% if current_user != user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: options[:class].presence || "btn btn-primary" %>
  <% else %>
    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: options[:class].presence || "btn bbtn-primary" %>
  <% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render "/users/index", users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render "/users/index", users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>